services:
  mdm:
    image: mission-data-manager:latest
    ports: ["8080:8080"]

  gateway:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../../creds:/etc/nginx/tls:ro           
    ports: ["443:443"]
    depends_on: [mdm]

  edge-jsbsim:
    build: ../../edge/jsbsim
    env_file: ../../edge/jsbsim/.env
    volumes:
      - ../../creds:/app/tls:ro                 
      - ../../edge/jsbsim/scripts:/app/scripts:ro
    depends_on: [gateway]
