services:
  mdm:
    image: cweber12/mission-data-manager:0.1.0
    restart: unless-stopped
    environment:
      - MDM_PORT=50052
      - LOG_LEVEL=info
    ports:
      - "50052:50052"

  gateway:
    image: nginx:alpine
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: ../../creds
        target: /etc/nginx/tls
        read_only: true
    ports: ["443:443"]
    depends_on: [mdm]

  edge-jsbsim:
    build: ../../edge-jsbsim
    env_file: ../../.env
    volumes:
      - ../../creds:/app/tls:ro
      - ../../edge-jsbsim/scripts:/app/scripts:ro
    depends_on: [gateway]
