name: CI

on:
  push:
  pull_request:

jobs:
  proto-build-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          protoc --version
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Python protoc plugins
        run: |
          python -m pip install --upgrade pip
          pip install grpcio grpcio-tools
      - name: Generate Python stubs
        run: |
          mkdir -p gen/python
          python -m grpc_tools.protoc -I proto \
            --python_out=gen/python \
            --grpc_python_out=gen/python \
            proto/telemetry.proto proto/detections.proto
      - name: Sanity import
        run: |
          python -c "import sys, pathlib; sys.path.insert(0, str(pathlib.Path('gen/python').resolve())); import telemetry_pb2, telemetry_pb2_grpc, detections_pb2, detections_pb2_grpc; print('Imports OK')"

  e2e-smoke:
    needs: proto-build-python
    runs-on: windows-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create venv + deps
        shell: pwsh
        run: |
          py -m venv .venv
          .\.venv\Scripts\Activate.ps1
          python -m pip install --upgrade pip
          pip install grpcio grpcio-tools

      - name: Generate Python stubs (PowerShell)
        shell: pwsh
        run: |
          .\.venv\Scripts\Activate.ps1
          .\scripts\make_proto.ps1
          python -c "import sys, pathlib; sys.path.insert(0, str(pathlib.Path('gen/python').resolve())); import telemetry_pb2, telemetry_pb2_grpc, detections_pb2, detections_pb2_grpc; print('Imports OK')"

      - name: Make test certs
        shell: pwsh
        run: |
          .\.venv\Scripts\Activate.ps1
          .\scripts\make_certs.ps1
          Get-ChildItem creds

      # Launch Ground (bg) with mTLS and real log files
      - name: Launch Ground (bg, TLS)
        shell: pwsh
        run: |
          .\.venv\Scripts\Activate.ps1
          $env:PYTHONPATH = (Join-Path (Get-Location) 'gen\python')
          $env:TLS = "1"
          $env:CERT_DIR = (Join-Path (Get-Location) 'creds')
          $env:HOST = "127.0.0.1"
          $env:PORT = "50051"
          $env:GRPC_VERBOSITY = "DEBUG"
          $env:GRPC_TRACE = "handshaker,security_handshaker,tcp"
          Start-Process -FilePath .\.venv\Scripts\python.exe `
            -ArgumentList '-u','-m','ground.server' `
            -NoNewWindow `
            -RedirectStandardOutput ground.out.log `
            -RedirectStandardError ground.err.log `
            -WorkingDirectory (Get-Location) `
            -PassThru | Select-Object -ExpandProperty Id | Out-File ground.pid -Encoding ascii -NoNewline
          Start-Sleep -Seconds 8
          Write-Host "Ground server started"

      # Wait for Ground to be ready for gRPC connections
      - name: Wait for Ground gRPC readiness
        shell: pwsh
        run: |
          .\.venv\Scripts\Activate.ps1
          $env:PYTHONPATH = (Join-Path (Get-Location) 'gen\python')
          $maxAttempts = 10
          $delay = 5
          $success = $false
          for ($attempt = 1; $attempt -le $maxAttempts; $attempt++) {
            try {
              $tcp = New-Object System.Net.Sockets.TcpClient
              $tcp.Connect("127.0.0.1", 50051)
              $tcp.Close()
              Write-Host "TCP connection successful"
              $success = $true
              break
            } catch {
              Write-Host "Attempt $attempt: TCP not ready, waiting $delay seconds..."
              Start-Sleep -Seconds $delay
            }
          }
          if (-not $success) {
            Write-Error "Ground server never became ready for TCP connections"
            exit 1
          }
          Write-Host "Ground server is ready for gRPC connections"

      # Run Edge client (foreground), log to file
      - name: Run Python Edge (mTLS)
        shell: pwsh
        env:
          TLS: "1"
          CERT_DIR: "creds"
          TLS_OVERRIDE_HOST: "localhost"
        run: |
          .\.venv\Scripts\Activate.ps1
          $env:PYTHONPATH = (Join-Path (Get-Location) 'gen\python')
          
          Write-Host "Starting Edge client..."
          try {
              python -u -m edge.client 2>&1 | Tee-Object edge_py.log
              if ($LASTEXITCODE -ne 0) { 
                  throw "Edge client failed with exit code: $LASTEXITCODE" 
              }
              Write-Host "Edge client completed successfully"
          } catch {
              Write-Host "Edge client failed: $($_.Exception.Message)"
              Write-Host "===== edge_py.log ====="
              Get-Content edge_py.log -ErrorAction SilentlyContinue | Out-Host
              throw
          }

      - name: Verify acks
        shell: pwsh
        run: |
          Write-Host "Verifying acknowledgments in edge_py.log..."
          
          $telemetryAck = Select-String -Path edge_py.log -Pattern "\[edge\] telemetry ack=True" -Quiet
          $detectionsAck = Select-String -Path edge_py.log -Pattern "\[edge\] detections ack=True" -Quiet
          
          if (-not $telemetryAck) {
              Write-Error "Telemetry acknowledgment not found in logs"
              Get-Content edge_py.log | Out-Host
              exit 1
          }
          
          if (-not $detectionsAck) {
              Write-Error "Detections acknowledgment not found in logs"
              Get-Content edge_py.log | Out-Host
              exit 1
          }
          
          Write-Host "All acknowledgments verified successfully"

      - name: Show logs on failure
        if: failure()
        shell: pwsh
        run: |
          Write-Host "===== ground.out.log (last 200) ====="
          Get-Content ground.out.log -Tail 200 -ErrorAction SilentlyContinue | Out-Host
          Write-Host "===== ground.err.log (last 200) ====="
          Get-Content ground.err.log -Tail 200 -ErrorAction SilentlyContinue | Out-Host
          Write-Host "===== edge_py.log (last 200) ====="
          Get-Content edge_py.log -Tail 200 -ErrorAction SilentlyContinue | Out-Host
          Write-Host "===== netstat :50051 ====="
          netstat -ano | Select-String -Pattern ":50051" | Out-Host
      
      # Teardown
      - name: Stop Ground
        if: always()
        shell: pwsh
        run: |
          if (Test-Path ground.pid) {
            $groundPid = [int](Get-Content ground.pid)
            Write-Host "Stopping Ground PID $groundPid"
            Stop-Process -Id $groundPid -ErrorAction SilentlyContinue
            Write-Host "Ground server stopped"
          }

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-logs
          path: |
            ground.out.log
            ground.err.log
            edge_py.log