name: CI

on:
  push:
  pull_request:

jobs:
  proto-build-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          protoc --version

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python protoc plugins
        run: |
          python -m pip install --upgrade pip
          pip install grpcio grpcio-tools

      - name: Generate Python stubs
        run: |
          mkdir -p gen/python
          python -m grpc_tools.protoc -I proto \
            --python_out=gen/python \
            --grpc_python_out=gen/python \
            proto/telemetry.proto proto/detections.proto

      - name: Sanity import (ensure stubs import cleanly)
        run: |
          python - << 'PY'
          import sys, pathlib
          sys.path.insert(0, str(pathlib.Path("gen/python").resolve()))
          import telemetry_pb2, telemetry_pb2_grpc
          import detections_pb2, detections_pb2_grpc
          print("Imports OK:", telemetry_pb2.__name__, detections_pb2.__name__)
          PY

      - name: Basic lint (EOL/CRLF check)
        run: test -z "$(git ls-files --eol | grep 'crlf')"