name: CI

on:
  push:
  pull_request:

jobs:
  proto-build-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          protoc --version
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Python protoc plugins
        run: |
          python -m pip install --upgrade pip
          pip install grpcio grpcio-tools
      - name: Generate Python stubs
        run: |
          mkdir -p gen/python
          python -m grpc_tools.protoc -I proto \
            --python_out=gen/python \
            --grpc_python_out=gen/python \
            proto/telemetry.proto proto/detections.proto
      - name: Sanity import
        run: |
          python -c "import sys, pathlib; sys.path.insert(0, str(pathlib.Path('gen/python').resolve())); import telemetry_pb2, telemetry_pb2_grpc, detections_pb2, detections_pb2_grpc; print('Imports OK')"

  e2e-smoke:
    needs: proto-build-python
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Create venv + install deps
      - name: Setup venv
        shell: pwsh
        run: |
          py -m venv .venv
          .\.venv\Scripts\Activate.ps1
          python -m pip install --upgrade pip
          pip install grpcio grpcio-tools

      # Generate stubs using your PowerShell script
      - name: Generate Python stubs (PowerShell)
        shell: pwsh
        run: |
          .\.venv\Scripts\Activate.ps1
          .\scripts\make_proto.ps1
          # sanity: stubs import check
          python -c "import sys, pathlib; sys.path.insert(0, str(pathlib.Path('gen/python').resolve())); import telemetry_pb2, telemetry_pb2_grpc, detections_pb2, detections_pb2_grpc; print('Imports OK')"

      # Make dev certs using your PowerShell script
      - name: Make dev certs for mTLS (PowerShell)
        shell: pwsh
        run: |
          .\.venv\Scripts\Activate.ps1
          .\scripts\make_certs.ps1
          Get-ChildItem creds | Out-Host

            # Launch Ground (TLS) in background with explicit WorkingDirectory
      - name: Launch Ground (bg, TLS)
        shell: pwsh
        run: |
          $env:PYTHONPATH = (Join-Path (Get-Location) 'gen\python')
          $env:TLS = "1"; $env:CERT_DIR = "creds"; $env:BIND_ADDR = "127.0.0.1"
          $python = ".\.venv\Scripts\python.exe"
          $p = Start-Process -FilePath $python `
                -ArgumentList '-u','-m','ground.server' `
                -NoNewWindow `
                -RedirectStandardOutput ground.out.log `
                -RedirectStandardError ground.err.log `
                -WorkingDirectory (Get-Location) `
                -PassThru
          $p.Id | Out-File ground.pid -Encoding ascii
          Start-Sleep -Seconds 5
          Get-Content ground.out.log -TotalCount 50 -ErrorAction SilentlyContinue | Out-Host
          Get-Content ground.err.log -TotalCount 50 -ErrorAction SilentlyContinue | Out-Host
          
          # Check if process is still running
          if (-not (Get-Process -Id $p.Id -ErrorAction SilentlyContinue)) {
              Write-Error "Ground server process died during startup"
              Get-Content ground.out.log -ErrorAction SilentlyContinue | Out-Host
              Get-Content ground.err.log -ErrorAction SilentlyContinue | Out-Host
              exit 1
          }

      - name: Wait for Ground via gRPC (mTLS)
        shell: pwsh
        run: |
          .\.venv\Scripts\Activate.ps1
          $env:PYTHONPATH = (Join-Path (Get-Location) 'gen\python')
          python scripts\probe_tls.py --addr 127.0.0.1:50051 --cert-dir creds --override-host localhost --timeout 30
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

      - name: Show Ground logs on failure
        if: failure()
        shell: pwsh
        run: |
          Write-Host "===== ground.out.log (last 200) ====="
          Get-Content ground.out.log -Tail 200 -ErrorAction SilentlyContinue | Out-Host
          Write-Host "===== ground.err.log (last 200) ====="
          Get-Content ground.err.log -Tail 200 -ErrorAction SilentlyContinue | Out-Host
          Write-Host "===== netstat :50051 ====="
          netstat -ano | Select-String -Pattern ":50051" | Out-Host
          Write-Host "===== Ground process status ====="
          if (Test-Path ground.pid) {
              $pid = Get-Content ground.pid
              Write-Host "Ground PID: $pid"
              Get-Process -Id $pid -ErrorAction SilentlyContinue | Out-Host
          }

      # Python Edge (TLS)
      - name: Run Python Edge (TLS)
        shell: pwsh
        run: |
          .\.venv\Scripts\Activate.ps1
          $env:PYTHONPATH = (Join-Path (Get-Location) 'gen\python')
          $env:TLS = "1"; $env:CERT_DIR = "creds"
          $env:ADDR = "127.0.0.1:50051"
          $env:TLS_OVERRIDE_HOST = "localhost"
          python -u -m edge.client 2>&1 | Tee-Object -FilePath edge_py.log
          if ($LASTEXITCODE -ne 0) { Write-Error "Python Edge failed"; exit $LASTEXITCODE }

      - name: Verify Python acks
        shell: pwsh
        run: |
          if (-not (Select-String -Path edge_py.log -Pattern "\[edge\] telemetry ack=True" -Quiet)) { Write-Error "Telemetry ack missing"; exit 1 }
          if (-not (Select-String -Path edge_py.log -Pattern "\[edge\] detections ack=True" -Quiet)) { Write-Error "Detections ack missing"; exit 1 }
          Write-Host "Python Edge acks found."

      # Optional Node Edge (TLS)
      - uses: actions/setup-node@v4
        if: ${{ hashFiles('edge-node/client.js') != '' }}
        with:
          node-version: "18"

      - name: Node install
        if: ${{ hashFiles('edge-node/client.js') != '' }}
        shell: pwsh
        working-directory: edge-node
        run: npm ci || npm install --no-audit --no-fund

      - name: Run Node Edge (TLS)
        if: ${{ hashFiles('edge-node/client.js') != '' }}
        shell: pwsh
        run: |
          $env:TLS = "1"; $env:CERT_DIR = "creds"
          node edge-node\client.js 2>&1 | Tee-Object -FilePath edge_node.log
          if ($LASTEXITCODE -ne 0) { Write-Error "Node Edge failed"; exit $LASTEXITCODE }

      - name: Verify Node acks
        if: ${{ hashFiles('edge-node/client.js') != '' }}
        shell: pwsh
        run: |
          if (-not (Select-String -Path edge_node.log -Pattern "\[node-edge\] telemetry ack= true" -Quiet)) { Write-Error "Node telemetry ack missing"; exit 1 }
          if (-not (Select-String -Path edge_node.log -Pattern "\[node-edge\] detections ack= true" -Quiet)) { Write-Error "Node detections ack missing"; exit 1 }
          Write-Host "Node Edge acks found."

      # Teardown & artifacts
      - name: Stop Ground
        if: always()
        shell: pwsh
        run: |
          if (Test-Path ground.pid) {
            $srvPid = Get-Content ground.pid
            Write-Host "Killing Ground PID $srvPid"
            Stop-Process -Id $srvPid -ErrorAction SilentlyContinue
          }

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-logs
          path: |
            ground.out.log
            ground.err.log
            edge_py.log
            edge_node.log
          if-no-files-found: ignore